version: "3.9"
services:
    web:
        build: 
            context: ./
            dockerfile: ./web/Dockerfile
        ports:
            - "5000:5000"
        env_file: "./.env"
        volumes:
            - np-databridge-volume:/data-dir

    
    job:
        build:
            context: ./
            dockerfile: ./job/Dockerfile
        env_file: "./.env"
        volumes:
            - np-databridge-volume:/data-dir
volumes: 
    np-databridge-volume:
        
    
    